name: "flake8 (plugins support)"
description: "Run flake8 with optional plugins."
inputs:
  options:
    description: "Options passed to flake8. Use `flake8 --help` to print available."
    required: false
    default: "--format pylint"
  src:
    description: "File or directory to run flake8 on."
    required: false
    default: "."
  plugins:
    description: "List of flake8 plugins to use."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.options }}
    - ${{ inputs.src }}
    - ${{ inputs.plugins }}
  pre-entrypoint: "/setup.sh"
  entrypoint: "/run.sh"
branding:
  icon: "check"
  color: "gray-dark"
